POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzYyNTg5MjUsInVzZXJJZCI6MX0.pCTjabj_fWU1V662PJtdI7DzgvALFEaxT13VJg6tBoE

{
    "name": "Test event 2",
    "description": "A test event!!!",
    "location": "A test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}