DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzYyNTg5MjUsInVzZXJJZCI6MX0.pCTjabj_fWU1V662PJtdI7DzgvALFEaxT13VJg6tBoE