PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM2MjU4NjcxLCJ1c2VySWQiOjJ9.K3qzV4hRxIaiwrtPTbW7XbbAbt6qX1ELxCAaRgn5wE0

{
    "name": "updated test event",
    "description": "New description",
    "location": "A test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}